Repository pento/testpress, pull requests merged in 2019-04, with the labels that each got.

#141 Fix support for Docker Toolbox
  src/services/docker/index.js
Labels: [Platform] Windows, [Service] Docker, [Type] Bug

#124 Fix light theme colours
  src/app/style.scss
  src/components/about-panel/style.scss
  src/components/pages/style.scss
  src/components/preferences-panel/style.scss
  src/components/status-panel/style.scss
  src/components/tabs/style.scss
  src/index.scss
Labels: [Type] Bug

#125 Disable 'Open Docker' button after you click it
  src/components/status-panel/missing-daemon-info.js
Labels: [Type] Bug

#121 Fix external links
  src/components/about-panel/index.js
  src/components/about-panel/style.scss
  src/components/external-link/index.js
  src/components/external-link/style.scss
  src/components/status-panel/missing-daemon-info.js
  src/components/status-panel/missing-folder-info.js
  src/components/status-panel/ready-info.js
  src/components/status-panel/style.scss
Labels: [Type] Bug

#142 Add Windows build config
  assets/icon.ico
  package.json
Labels: [Platform] Windows, [Type] Enhancement

#126 This adds dark buttons
  src/app/style.scss
Labels: [Type] Bug

#139 Add GitHub documentation and templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/readme.md
  docs/release.md
Labels: [Type] Task

#129 Ensure the Docker containers are shutdown on exit.
  src/services/docker/index.js
Labels: [Type] Bug

#144 Add bottom tray support
  src/app/style.scss
  src/electron-runner.js
Labels: [Platform] Windows, [Type] Bug
